
// ****Auto generated by syn

use super::types::*;
use crate::types::*;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use serde_with::serde_as;
#[cfg(feature = "reflect")]
use bevy_reflect::{Reflect, Struct, DynamicStruct, Typed, std_traits::ReflectDefault};
use sea_orm::{DatabaseBackend, QueryTrait, Schema};
use crate::orm::traits::DbOpTrait;
#[cfg(feature = "reflect")]
use crate::orm::traits::ReflectDbOpTrait;
use crate::impl_db_op_trait;


        #[serde_as]
#[derive(Serialize, Deserialize, Clone, Debug, Default, DeriveEntityModel)]
#[sea_orm(table_name = "BOX")]
#[cfg_attr(feature = "reflect", derive(Reflect))]
#[cfg_attr(feature = "reflect", reflect(Default, DbOpTrait))]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub REFNO: RefU64,
    pub NAME: String,
    pub OWNER: RefU64,
    pub TYPE: String,
    pub LEVE: I32Vec,
    pub LOCK: bool,
    pub OBST: i32,
    pub ORI: F32Vec,
    pub ORRF: String,
    pub POS: F32Vec,
    pub PURP: String,
    pub REPCOU: i32,
    pub TMRREF: String,
    pub XLEN: f32,
    pub YLEN: f32,
    pub ZLEN: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
impl ActiveModelBehavior for ActiveModel {}

impl_db_op_trait!();
        